### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by d-beck** [ablestar/ablestar-cli#21]
When installing the project there's a vulnerability reported in a dependency:

![image](https://github.com/ablestar/ablestar-cli/assets/8495236/2847c9e1-f3d1-4874-9faa-e83f006a3ef7)

The relevant output in `npm audit` seems to be:

```
xlsx  *
Severity: high
Prototype Pollution in sheetJS - https://github.com/advisories/GHSA-4r6h-8v6p-xvw6
```

If it's not too much work can we find a way to fix this?

**Comment by tewshi** [comment]
I think this issue fixed on #22 , Please close this issue @d-beck
