### ISSUE TITLE
Error : Cannot destructure property 'itemKey' of 'Object.values(...).find(...)' as it is undefined.

### ISSUE THREAD

**Issue by Dhanush-gitt** [ablestar/ablestar-cli#23]
**Describe the bug**
I exported products in matrixify format and when I try to import the products the cli throws this Error: Cannot destructure property 'itemKey' of 'Object.values(...).find(...)' as it is undefined.

**To Reproduce**
1. run ablestar-cli command
2. Export Products in Matrixify format
3. Make changes to the data and Import the file in Matrixify format

**Expected behavior**
Should Import the products with any error.

**Screenshots**
![image](https://github.com/ablestar/ablestar-cli/assets/114050393/2952192e-8d04-4b1d-a65e-f5a606edef37)
![image](https://github.com/ablestar/ablestar-cli/assets/114050393/b18557db-79e0-4fc3-b44c-8cdc662b5849)

**Desktop (please complete the following information):**
 - OS: windows 11

**Comment by d-beck** [comment]
Hi @Dhanush-gitt thank you for raising the issue. I think the product imports is one of the ones we still need to implement. (We've been starting with simpler ones like collections, pages, blogs etc..). 

I've created #24 to track that and we'll also make it more clear within the tool/documentation which imports we've implemented yet.
